{
	title: 'Csakis Családos Keresztény Fesztivál!',
	greeting: 'Welcome!',
	subtitle: 'We love Jesus!',
	section_one_title: 'CSAKIS idén is!',
	section_one_body_text: 'CSAKIS idén is!\n\nII. CSAKIS Családos Keresztény Fesztivál Kézdivásárhelyen\n\n\nÖrömmel értesítjük, hogy Székelyföldön, Kézdivásárhelyen, 2017. július 7.- 9. között második alkalommal szervezzük meg a Családos Keresztény Fesztivált.\nE sportcsarnokban és környékén megtartandó eseménnyel egy nyári pihenési és töltekezési lehetőséget szeretnénk biztosítani a családoknak. Fesztiválunk programja és légköre kimondottan Keresztény lesz, ahol áhítatokkal, előadásokkal, lelkigondozói- és fórumbeszélgetésekkel kívánjuk erősíteni házasságainkat Isten segedelmével. Emellett sok játék, gyerekfoglalkozás, ifjúsági program, vetélkedő, sport és koncertek várnak kedves vendégeinkre.\nA fesztivál fő előadója Dr. Komlósi Piroska családterapeuta, nagycsaládos családgondozó. Esténként zenei élményt szolgáltat, dicsőítést vezet a Reménység együttes, Csiszér László és Szabó Balázs.\nA bejelentkező családoknak tudunk segíteni az étkezés és szállás megszervezésében, illetve kisérőprogramok kínálásával fesztiválunk előtt és után.\nHamarosan részletes programmal jelentkezünk, amelyet a http://www.csakis.net/ oldalon, illetve az esemény Facebook oldalán teszünk közzé a Csakis Családos Keresztény Fesztivál név alatt.\nVárunk szeretettel minden családot,\nA szervező csapat',
	section_two_title: 'Kézdivásárhelyi Sportcsarnok és környéke',
	section_two_body_text: 'itt vagyunk. google map link itt van.',
	section_three_title: 'Magunkról',
	section_three_body_text: 'A Kézdivásárhelyi Családos Keresztény Fesztivállal egy nyári pihenési és töltekezési lehetőséget szeretnénk biztosítani a családoknak. Mivel a családok nyaranta rengeteg kikapcsolódási lehetőség közül válogathatnak, ezért a mi fesztiválunk programja és légköre kimondottan keresztény lesz. Kirándulási, kikapcsolódási, töltekezési és sportolási lehetőségek mellett a házasságot érintő gondolatébresztőkön, előadásokon, életút beszélgetéseken vehetnek részt a fesztiválra látogatók. Természetesen a fesztiválok elvárásainak eleget téve koncertekre is sor kerül, de dicsőítésre, példaértékű családokkal fórumbeszélgetésekre, élményszínházra és egyéb alternatív programokra is sor kerül a rendezvényen. Mivel a család egészének kínálunk programot, ezért a gyerekek, ifjak részére külön programot is szervezünk, ahol ki-ki a korosztályának megfelelő tevékenységekbe kapcsolódhat be.',
	section_three_map_link: 'http://google.com',
	$section_one_body_text_type: 'textarea',
	section_one_image: 'https://scontent.fsbz1-2.fna.fbcdn.net/v/t31.0-8/13920430_1754485428163162_5558796261105781116_o.jpg?oh=e7b4339b9e7171aaa97aeed4fb11aa5b&oe=599575A5',
	$section_one_image_type: 'image',
	section_two_image: 'https://scontent.fsbz1-2.fna.fbcdn.net/v/t31.0-8/14068400_1756894361255602_6747156726755247737_o.jpg?oh=58fb3ef56d9dbf53946b39b7d5e961e5&oe=59628B05',
	$section_two_image_type: 'image',
	section_three_image: 'https://scontent.fsbz1-2.fna.fbcdn.net/v/t31.0-8/14053906_1756874574590914_2684962774103647908_o.jpg?oh=0a8ee83a442abc9aac3810aa28fb2f65&oe=5957CEE1',
	$section_three_image_type: 'image',
	section_four_image: 'https://scontent.fsbz1-2.fna.fbcdn.net/v/t31.0-8/13996078_1756872901257748_1536140789836697260_o.jpg?oh=79b1501c8124e4a22b279da08fc65015&oe=5957C7CA',
	$section_four_image_type: 'image',
	$banner_image_type: 'image',
	banner_image: 'http://res.cloudinary.com/csakis-fesztival/image/upload/v1492525308/CSAKISwebbanner_tdtw3v.png',
	$logo_type: 'image',
	logo: 'http://res.cloudinary.com/csakis-fesztival/image/upload/v1491554139/CSAKISsquareTRANSPARENTjustlogo_f90dn3.png'
}