{
	title: 'Csakis Családos Keresztény Fesztivál!',
	greeting: 'Welcome!',
	subtitle: 'We love Jesus!',
	section_one_title: 'Péntek | Július 6',
	section_one_body_text: '16:00 -17:00 - Regisztráció \n<br/><br/>  16:00 - 18:00 - Kézműves foglalkozás  a Zöld Nap Egyesület szervezésében \n<br/>  <br/> 18:00 - 18:30 – Megnyitó\n<br/> &nbsp; &nbsp; &nbsp; - Eligazítás | Vinczi Botond lelkipásztor\n<br/> &nbsp;&nbsp; &nbsp; - Családos esti ima\n<br/> <br/> 18:30 - 19:30 - Vacsora \n<br/> <br/> 19:30-20:30-Koncert | Kovászna Belvárosi  ifjúsági Zenekar\n<br/> <br/> 20:30 - 21:30 - Dicsőités tábortűz mellett',
	section_two_title: 'Szombat | Július 7',
	section_two_body_text: '10:00 - 10:30 - Hangoló | Ruszka Sándor és Margó   <br/> <br/> 10:30 - 13:00 - Gyermekfoglalkozás | 4 - 12 éves gyerekeknek, 2 csoportban | Ifjúsági program   <br/> <br/> 10:30 - 11:30 – Előadás | Dr. Horváth Levente és Mária|Mire jó a házasság? <br/> <br/> 11:30 - 12:00 - Páros beszélgetés a házaspároknak   <br/> <br/> 12:00 - 13:00 - Kérdések | Válaszok |  Dr. Horváth Levente és Mária <br/> <br/> 13:00 -15:00 - Ebéd  <br/> <br/> 15:00 -17:00 - Családos vetélkedők a Pro Pectus Egyesület szervezésében   <br/> <br/>17:00-18:30- Előadás | Gyereknevelés |Mit adhatok gyermekemnek?<br/> <br/> 18:30 - 19:30 – Vacsora  <br/> <br/> 19:30 - <strong>Flashmob </strong>  a családokért  <br/> <br/>  19:45 - 20:15 - Áhitat | Müller Loránd lelkipásztor <br/> <br/> 20:20 - 22:00 - Koncert | <strong> Csiszér László <br/> <br/>Programunkat gazdagítják a különféle sporttevékenységek ,  lovaglás <br/>és a Benji Állatvédő Egyesület által biztosított állatsimogató.<br/>  A rendezvény teljes ideje alatt imaszoba és babaszoba áll rendelkezésre a résztvevők számára .',
	section_three_title: '',
	section_three_body_text: '',
	$section_one_body_text_type: 'textarea',
	section_one_image: '',
	$section_one_image_type: 'image',
	section_two_image: '',
	$section_two_image_type: 'image',
	section_three_image: '',
	$section_three_image_type: 'image',
	$banner_image_type: 'image',
	banner_image: '',
	$logo_type: 'image',
	logo: 'http://res.cloudinary.com/csakis-fesztival/image/upload/v1491554139/CSAKISsquareTRANSPARENTjustlogo_f90dn3.png'
}