{
	title: 'Csakis Családos Keresztény Fesztivál!',
	greeting: 'Welcome!',
	subtitle: 'We love Jesus!',
	section_one_title: 'Péntek | Július 7',
	section_one_body_text: '16:00 -18:00 - Regisztráció \n<br/><br/> \n17:00-18:30- Kerékpárverseny fiataloknak (ügyességi próbák)- bukósisak használata kötelező\n<br/><br/> \n 16:00 - 18:00 - Kézműves foglalkozás & kincskeresés a Zöld Nap Egyesület szervezésében \n<br/> <br/> 18:00 - 19:00 - Vacsora \n<br/>  <br/> 19:00 - 20:00 – Megnyitó\n<br/> &nbsp; &nbsp; &nbsp; - Beder Imre lelkipásztor, Kerekes László plébános köszöntője \n<br/> &nbsp; &nbsp; &nbsp; - Eligazítás | Vinczi Botond lelkipásztor\n<br/> &nbsp;&nbsp; &nbsp; - Családos esti ima\n<br/> <br/> 20:00 - 22:00 - Koncert | <strong> Reménység Együttes </strong>',
	section_two_title: 'Szombat | Július 8',
	section_two_body_text: '10:00 - 10:30 - Hangoló | Ruszka Sándor és Margó  <br/> <br/> 10:30 - 13:00 - Gyermekfoglalkozás | 4 - 12 éves gyerekeknek, 2 csoportban | Ifjúsági program  <br/> <br/> 10:30 - 11:30 – Előadás | Dr. Komlósi Piroska | “Vele megelégszem” I.  <br/> <br/> 11:30 - 12:00 - Páros beszélgetés a házaspároknak  <br/> <br/> 12:00 - 13:00 - Kérdések | Válaszok | Dr. Komlósi Piroska válaszol  <br/> <br/> 13:00 -15:00 - Ebéd <br/> <br/> 15:00 -17:00 - Családos vetélkedők a Pro Pectus Egyesület szervezésében  <br/> <br/>17:00-18:30- Kerékpárverseny gyerekeknek (ügyességi próbák)- bukósisak használata kötelező <br/> <br/> 16:00 - 17:00 - Előadás | Ráczné Komlósi Virág | “Így neveld a sárkányodat!” | a kamaszkor  előszeléig  <br/> <br/> 17:00 -19:00 - Előadás| Szénégető István családreferens | “Veled kiteljesedve”  | kiscsoportos beszélgetések  <br/> <br/> 19:00 - 20:00 – Vacsora <br/> <br/> 19:45 - <strong>Flashmob </strong>  a családoskért <br/> <br/>  20:00 - 20:15 - Családos esti ima<br/> <br/> 20:20 - 22:00 - Koncert | <strong> Csiszér László</strong>',
	section_three_title: 'Vasárnap | Július 9',
	section_three_body_text: '10:00 - 10:30 - Hangoló | Orbán Lajos lelkipásztor   <br/> <br/> 10:30 - 13:00 - Gyermekfoglalkozás | 4 - 12 éves gyerekeknek, 2 csoportban | Ifjúsági program   <br/> <br/> 10:30 - 11:30 – Előadás | Dr. Komlósi Piroska | “Vele megelégszem” II.   <br/>  <br/> 11:30 - 12:00 - Páros beszélgetés a házaspároknak   <br/>  <br/> 12:00 - 13:00 - Kérdések | válaszok | Dr. Komlósi Piroska válaszol  <br/><br/> 13:00 -15:00 - Ebéd   <br/>  <br/> 14:00 - 15:00 – Előadás | Ráczné Komlósi Virág | “Így neveld a sárkányodat!” | a kamaszkor  viharában  <br/>  <br/> 15:00 -17:00 - Családos játékok   <br/>  <br/> 16:30 - 18:30 – Előadás | Ruszka Sándor és Margó | Házassági sérüléseink | Kiscsoportos beszélgetések   <br/>  <br/> 18:30 - 19:30 - Vacsora   <br/>  <br/> 19:30 - 20:00 - Családos esti ima  | Záró gondolatok | Vinczi Botond lelkipásztor  <br/>  <br/>  20:00 - 22:00 - Koncert | Szabó Balázs < br/>  <br/>  Programunkat gazdagítják a különféle sporttevékenységek és a lovaglás.   <br/>  <br/> A rendezvény teljes ideje alatt imaszoba áll rendelkezésre a résztvevők számára.  <br/> Részvételi díj | 20 RON/ család  & 10 RON/ személy',
	$section_one_body_text_type: 'textarea',
	section_one_image: 'http://res.cloudinary.com/csakis-fesztival/image/upload/v1492542146/Csakis-3-48_hfjzdn.jpg',
	$section_one_image_type: 'image',
	section_two_image: 'https://scontent.fsbz1-2.fna.fbcdn.net/v/t31.0-8/14068400_1756894361255602_6747156726755247737_o.jpg?oh=58fb3ef56d9dbf53946b39b7d5e961e5&oe=59628B05',
	$section_two_image_type: 'image',
	section_three_image: 'http://res.cloudinary.com/csakis-fesztival/image/upload/v1492542148/Csakis-2-10xx_he9dat.jpg',
	$section_three_image_type: 'image',
	$banner_image_type: 'image',
	banner_image: '',
	$logo_type: 'image',
	logo: 'http://res.cloudinary.com/csakis-fesztival/image/upload/v1491554139/CSAKISsquareTRANSPARENTjustlogo_f90dn3.png'
}